export { default as Header } from './Header';
export { default as Main } from './Main';
export { default as Info } from './Info';
export { default as Partners } from './Partners';
export { default as Intro } from './Intro';
export { default as Payment } from './Payment';
export { default as More } from './More';
export { default as Footer } from './Footer';
export { default as Separator } from './Separator';